#!/usr/bin/bash
echo Enable Denvor Processor...
sudo sh -c 'echo 1 > /sys/devices/system/cpu/cpu1/online'
sudo sh -c 'echo 1 > /sys/devices/system/cpu/cpu2/online'

echo CPU Freq. Init. starts...
echo cpu0\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor'

echo cpu1\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor'

echo cpu2\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor'

echo cpu3\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor'

echo cpu4\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor'

echo cpu5\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor'
echo CPU Freq. Init. ends...
echo 
echo GPU Freq. Init. starts...
echo GPU\'s govenor set to userspace...
sudo sh -c 'echo userspace > /sys/devices/gpu.0/devfreq/17000000.gp10b/governor'
sudo sh -c 'echo 1300500000 > /sys/devices/gpu.0/devfreq/17000000.gp10b/userspace/set_freq'
 
echo GPU Freq. Init. ends...
