#!/usr/bin/bash

echo CPU Freq. Init. starts...
echo cpu0\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor'
#sudo sh -c 'echo 2035200 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq'

echo cpu3\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor'
#sudo sh -c 'echo 2035200 > /sys/devices/system/cpu/cpu3/cpufreq/scaling_max_freq'

echo cpu4\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor'
#sudo sh -c 'echo 2035200 > /sys/devices/system/cpu/cpu4/cpufreq/scaling_max_freq'

echo cpu5\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor'
#sudo sh -c 'echo 2035200 > /sys/devices/system/cpu/cpu5/cpufreq/scaling_max_freq'

echo CPU Freq. Init. ends...
echo 
echo Trun off Receive Packet Steering...
sudo sh -c 'echo 39 > /sys/class/net/eth0/queues/rx-0/rps_cpus'
sudo sh -c 'echo 39 > /sys/class/net/eth0/queues/tx-0/xps_cpus'


echo GPU Freq. Init. starts...
echo GPU\'s govenor set to userspace...
sudo sh -c 'echo userspace > /sys/devices/gpu.0/devfreq/17000000.gp10b/governor'
sudo sh -c 'echo 1300500000 > /sys/devices/gpu.0/devfreq/17000000.gp10b/userspace/set_freq'
 
echo GPU Freq. Init. ends...

echo Disable Denvor Processor...
sudo sh -c 'echo 0 > /sys/devices/system/cpu/cpu1/online'
sudo sh -c 'echo 0 > /sys/devices/system/cpu/cpu2/online'
