#!/usr/bin/bash

echo CPU Freq. Init. starts...
echo cpu0\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor'

echo cpu1\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor'

echo cpu2\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor'

echo cpu3\'s govenor set to performance...
sudo sh -c 'echo performance > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor'
echo CPU Freq. Init. ends...
echo 
 
